name: gas3
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^6.1.6
  audioplayers: ^0.16.2
  screen: ^0.0.5
  syncfusion_flutter_gauges: ^18.3.48


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true