name: gas3
description: A Flutter project.
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  geolocator: ^7.0.3
  screen: ^0.0.5
  syncfusion_flutter_gauges: ^19.1.56
  auto_size_text: ^2.1.0
  audioplayers: ^0.18.3
  logger: ^1.0.0
  url_launcher: ^6.0.3
  flare_flutter: ^3.0.0
  shared_preferences: ^2.0.5
  flutter_colorpicker: ^0.4.0
  provider: ^5.0.0
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/speedIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/animation/
